site_name: Motion Rehabilitation
nav:
  - Motion Rehabilitation Software Overview: ap_er.md
theme:
  name: material
  features:
    - content.code.copy
  logo: assets/logo.png
plugins:
  - mkdocs-video
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  homepage: https://moretion.github.io/en/
