site_name: 魔迅科技文档中心
nav:
  - C++ SDK接口说明文档: cpp_sdk.md
theme: 
  name: material
  features:
    - content.code.copy
  logo: assets/logo.png
plugins:
    - mkdocs-video
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  homepage: https://moretion.github.io/